name: my first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome message
          run: echo "my first github actions job"

        - name: List files
          run: latest
        - name: Read files
          run: car README.md